######################### ROTAS DE AUTENTICAÇÃO #########################
### Criação de Usuário
POST  http://127.0.0.1:5000/register HTTP/1.1
Content-Type: application/json

{
        "id": 2,
        "email": "jose@email.com",
        "password": "jose"
}

### Autenticação do usuário
POST  http://127.0.0.1:5000/login HTTP/1.1
Content-Type: application/json

{
        "id": 2,
        "email": "jose@email.com",
        "password": "jose"
}

#########################################################################

############################# ROTAS DE POST #############################
### Post Administrador
POST  http://127.0.0.1:5000/post_administrators HTTP/1.1
Content-Type: application/json

{
        "id": 1,
        "login": "jose@email.com",
        "password": "jose"
}

### Post Neighborhood
POST  http://127.0.0.1:5000/post_neighborhoods HTTP/1.1
Content-Type: application/json

{
        "id": 2,
        "neighborhood_name": "teste2",
        "sector_name": "teste2"
}

### Post Nightguards
POST  http://127.0.0.1:5000/post_nightguard HTTP/1.1
Content-Type: application/json

{
        "id": 7,
        "name": "ailson",
        "vehicle": "titan656",
        "licenseplate": "abc-1234",
        "email": "ailson@email.com",
        "cpf": "000.000.000-00",
        "password": "ailson123",
        "dateofbirth": "2000-10-10",
        "formofpayment": "CREDITO"
}

### Post Sector
POST  http://127.0.0.1:5000/post_sectors HTTP/1.1
Content-Type: application/json

{
        "id": 1,
        "nightguard": "teste",
        "sector_name": "teste"
}


#########################################################################

########################## ROTAS DE GET GERAL ###########################
### Get Administrator
GET  http://127.0.0.1:5000/get_administrators HTTP/1.1
Content-Type: application/json

### Get Neighborhood
GET  http://127.0.0.1:5000/get_neighborhood HTTP/1.1
Content-Type: application/json

### Get Nightguard
GET  http://127.0.0.1:5000/get_nightguard HTTP/1.1
Content-Type: application/json

### Get Sectors
GET  http://127.0.0.1:5000/get_sector HTTP/1.1
Content-Type: application/json

#########################################################################

######################### ROTAS DE GET POR ID ###########################

### Get Administrator
GET  http://127.0.0.1:5000/get_administrators_by_id/1 HTTP/1.1
Content-Type: application/json

### Get Neighborhood
GET  http://127.0.0.1:5000/get_neighborhoods_by_id/1 HTTP/1.1
Content-Type: application/json

### Get Nightguard
GET  http://127.0.0.1:5000/get_nightguards_by_id/1 HTTP/1.1
Content-Type: application/json

### Get Sectors
GET  http://127.0.0.1:5000/get_sectors_by_id/1 HTTP/1.1
Content-Type: application/json

#########################################################################