### ROTAS ADMINISTRATORS 

### POSTS
POST  http://127.0.0.1:5000/administrators HTTP/1.1
Content-Type: application/json

{
        "login": "ailson",
        "id": 2,
        "password": "adm"
}

### DELETE
DELETE http://127.0.0.1:5000/administrators/1 HTTP/1.1
Content-Type: application/json

### GET 
GET http://127.0.0.1:5000/administrators HTTP/1.1
Content-Type: application/json

### PUT 
PUT http://127.0.0.1:5000/administrators/50 HTTP/1.1
Content-Type: application/json

{
        "login": "Ailson",
        "password": "1010"
        
        
}
###########################################################


### NIGHTGUARD - Rota de POST para CRIAÇÃO dos guardas.
POST http://127.0.0.1:5000/post_nightguard HTTP/1.1
Content-Type: application/json

{
    "name": "ROGER",
    "vehicle": "CB-500",
    "licenseplate": "RMR-1909",
    "email": "roger.rocha@gmail.com",
    "password": "cb123",
    "cpf": "987.654.321.00",
    "dateofbirth": "03/02/1980",
    "formofpayment": "dinheiro",
    "dateofpayment": "20",
    "district": "Azulville"
}
###########################################################

###########################################################
### ROTAS GET GERAIS
### NIGHTGUARD - Rota de GET para TODOS os guardas.
GET http://127.0.0.1:5000/get_nightguard?page=1&limit=6 HTTP/1.1
Content-Type: application/json

### NEIGHBORHOODS - Rota de GET para todos Bairro
GET http://127.0.0.1:5000/get_neighborhood HTTP/1.1
Content-Type: application/json

###########################################################


###########################################################
### ROTAS GET INDIVIDUAIS
### NEIGHBORHOODS - Rota de GET para um UNICO Setor
GET http://127.0.0.1:5000/sectors/1 HTTP/1.1
Content-Type: application/json

### NEIGHBORHOODS - Rota de GET para um UNICO Bairro
GET http://127.0.0.1:5000/neighborhoods/1 HTTP/1.1
Content-Type: application/json

###########################################################

###########################################################
### ROTAS PUT
### SECTORS - Rota de PUT para os Setores
PUT http://127.0.0.1:5000/sectors/1 HTTP/1.1
Content-Type: application/json

{
        "id": 5,
        "nightguard_name": "Ailson",
        "sector_name": "Setor 5"
}

###########################################################

###########################################################
### ROTAS DELETE


