######################### ROTAS DE AUTENTICAÇÃO #########################
### Criação de Usuário
POST  http://127.0.0.1:5000/register HTTP/1.1
Content-Type: application/json

{
        "id": 1,
        "password": "adm",
        "email": "adm@email.com"
}

### Autenticação do usuário
POST  http://127.0.0.1:5000/login HTTP/1.1
Content-Type: application/json

{
        "id": 1,
        "email": "adm@email.com",
        "password": "adm"
}

#########################################################################


