### alg
POST http://127.0.0.1:5000/night_guard HTTP/1.1
Content-Type: application/json

{
    "name": "ROGER",
    "vehicle": "CB-500",
    "licenseplate": "RMR-1909",
    "email": "roger.rocha@gmail.com",
    "password": "cb123",
    "cpf": "987.654.321.00",
    "dateofbirth": "03/02/1980",
    "formofpayment": "dinheiro",
    "dateofpayment": "20",
    "district": "Azulville"
}