"""alterando valores das  tabelas.

Revision ID: 19d1905f4981
Revises: 5322f68de8e4
Create Date: 2024-05-08 20:11:08.674809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19d1905f4981'
down_revision = '5322f68de8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nightguard', sa.String(length=255), nullable=False))
        batch_op.drop_column('neighborhood_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('neighborhood_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('nightguard')

    # ### end Alembic commands ###
