"""atualizando tabela de cliente.

Revision ID: 25f5220ad1a1
Revises: 83e9a3e671cf
Create Date: 2024-05-28 20:26:42.993205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25f5220ad1a1'
down_revision = '83e9a3e671cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=False)
        batch_op.alter_column('neighborhood',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=False)
        batch_op.alter_column('telephone',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=1024),
               existing_nullable=False)
        batch_op.alter_column('formofpayment',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('formofpayment',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('telephone',
               existing_type=sa.String(length=1024),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('neighborhood',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
