"""alterando valores das  tabelas.

Revision ID: 5322f68de8e4
Revises: 22b2f98e2ac8
Create Date: 2024-05-08 19:41:32.874501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5322f68de8e4'
down_revision = '22b2f98e2ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nightguard', schema=None) as batch_op:
        batch_op.alter_column('vehicle',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('licenseplate',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('cpf',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('formofpayment',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('neighborhood')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nightguard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('neighborhood', mysql.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('formofpayment',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('licenseplate',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('vehicle',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=False)

    # ### end Alembic commands ###
